import type { NextPage } from "next";
import Head from "next/head";
import { RandomFox } from "@/components/RandomFox";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">Hello World 😎!</h1>
        <RandomFox></RandomFox>
      </main>
      <footer></footer>
    </>
  );
};
export default Home;
